name = "NetworkLayout"
uuid = "46757867-2c16-5918-afeb-47bfcb05e46a"
version = "0.4.0"

[deps]
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
GeometryBasics = "0.3"
julia = "1"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["LightGraphs", "Test", "DelimitedFiles", "GeometryTypes"]
